"""Subprocess that owns one SSH/PTY session for a user's web terminal.

Problem solved:
    Previously the ``TerminalSession`` registry lived in a worker's
    memory. Under multi-worker Odoo deployments, subsequent polls
    from the browser could land on any worker, and N-1 of them
    returned 404 for the session. The fix is to move ownership of
    the SSH socket into this long-lived subprocess. Odoo workers
    become thin HTTP proxies that look up the subprocess port in
    ``cloud.terminal.route`` (backed by Postgres, shared state
    across workers).

Design:
    - One subprocess per terminal session.
    - Binds a random free port on 127.0.0.1 and prints it on the
      first line of stdout so the parent Odoo worker can record it
      in the route table before returning ``session_id`` to the UI.
    - Serves a tiny HTTP API (stdlib only) protected by a Bearer
      token generated by the parent and also stored in the route
      row. Each route has its own token so a compromised session
      cannot reach another.
    - Reuses ``TerminalSession`` verbatim — that class is
      deliberately free of Odoo imports so the subprocess can run
      without bootstrapping the full Odoo env (which would cost
      ~10 s per terminal open otherwise).
    - Exits on ``/close`` or when the session idle-times-out. The
      parent's cleanup cron evicts route rows whose PID is gone.

Invocation:
    python3 -m odoo.addons.incubacloud.terminal_subprocess \\
        --session-id <sid> \\
        --auth-token <hex> \\
        --config-file <path-to-json-with-ssh-kwargs-etc>

    The config file is read and deleted immediately so no secrets
    (the SSH private key) persist on disk beyond the first
    millisecond. CLI args are visible in ``ps aux`` which is why
    the SSH key does NOT go there.
"""
import argparse
import base64
import contextlib
import json
import logging
import os
import signal
import socket
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

# Run as a plain script (``python3 terminal_subprocess.py``), NOT as
# ``python3 -m incubacloud.terminal_subprocess`` — loading the
# ``incubacloud`` package would execute its ``__init__.py`` and pull
# in ``controllers``/``models``, which transitively import
# ``odoo.http``. With no Odoo boot in this process that import chain
# dies with a circular ``ImportError``. By putting our sibling dir
# on ``sys.path`` we can import ``terminal_session`` as a top-level
# module and skip the package init entirely.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import asyncssh  # noqa: E402

from terminal_session import TerminalSession  # noqa: E402

# Log to stderr of the parent Odoo worker — shows up in the Odoo
# container logs tagged with the session id prefix.
_logger = logging.getLogger("incubacloud.terminal_subprocess")


# Module-level globals populated by ``main()`` and read by the
# HTTP handler instances. ``http.server`` instantiates a handler
# per request so we can't stash state on ``self``.
_SESSION: TerminalSession | None = None
_AUTH_TOKEN: str = ""
_SERVER: ThreadingHTTPServer | None = None
_SHUTDOWN_LOCK = threading.Lock()


def _shutdown():
    """Tear down the HTTP server and the TerminalSession, then exit.

    Idempotent — the idle-watchdog thread and the ``/close`` handler
    can both race to call this; the lock ensures a single shutdown
    path runs.
    """
    global _SERVER, _SESSION
    with _SHUTDOWN_LOCK:
        if _SERVER is not None:
            # ``shutdown()`` must be called from a thread other than
            # the one running ``serve_forever`` — it is, because
            # every HTTP handler runs in its own thread.
            threading.Thread(target=_SERVER.shutdown, daemon=True).start()
            _SERVER = None
        if _SESSION is not None:
            with contextlib.suppress(Exception):
                _SESSION.close()
            _SESSION = None


def _watchdog():
    """Kill the subprocess once the session has been idle too long.

    ``TerminalSession.is_expired()`` checks ``SESSION_TIMEOUT`` against
    the last keystroke, not the last output, so long-running commands
    do not keep the watchdog at bay on an abandoned tab.
    """
    while True:
        time.sleep(30)
        if _SESSION is None:
            return
        if _SESSION.is_expired() or _SESSION.closed:
            _logger.info("terminal subprocess: session expired, shutting down")
            _shutdown()
            return


class _Handler(BaseHTTPRequestHandler):

    # Silence the default stderr log line per request — too noisy
    # under poll-every-second from the frontend. Errors still go
    # through the normal logger below.
    def log_message(self, format, *args):  # noqa: A002
        return

    # ── Helpers ─────────────────────────────────────────────────────

    def _auth_ok(self) -> bool:
        header = self.headers.get("Authorization", "")
        expected = f"Bearer {_AUTH_TOKEN}"
        return header == expected

    def _write_json(self, status: int, body: dict) -> None:
        payload = json.dumps(body).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def _read_json(self) -> dict:
        length = int(self.headers.get("Content-Length", "0") or 0)
        if not length:
            return {}
        raw = self.rfile.read(length)
        try:
            return json.loads(raw.decode("utf-8"))
        except Exception:
            return {}

    def _dispatch(self, method: str):
        if not self._auth_ok():
            self._write_json(401, {"ok": False, "error": "unauthorized"})
            return
        # ``self.path`` may contain a query string; only route on the
        # path component.
        path = self.path.split("?", 1)[0]
        handler = self._ROUTES.get((method, path))
        if handler is None:
            self._write_json(404, {"ok": False, "error": "not_found"})
            return
        try:
            handler(self)
        except Exception as exc:
            _logger.exception("terminal subprocess handler error")
            self._write_json(500, {"ok": False, "error": str(exc)})

    def do_GET(self):  # noqa: N802
        self._dispatch("GET")

    def do_POST(self):  # noqa: N802
        self._dispatch("POST")

    # ── Endpoints ──────────────────────────────────────────────────

    def _handle_state(self):
        s = _SESSION
        if s is None:
            self._write_json(200, {
                "ok": True, "connected": False, "closed": True,
                "close_reason": "gone", "error": None, "idle_seconds": 0,
            })
            return
        self._write_json(200, {
            "ok": True,
            "connected": s.connected,
            "closed": s.closed,
            "close_reason": s.close_reason,
            "error": s.error,
            "idle_seconds": int(s.idle_seconds()),
        })

    def _handle_output(self):
        s = _SESSION
        if s is None:
            self._write_json(200, {
                "ok": True, "chunks": [], "connected": False,
                "closed": True, "close_reason": "gone", "error": None,
                "idle_seconds": 0,
            })
            return
        # Parse ``?after=N`` from the query string.
        after = 0
        if "?" in self.path:
            for pair in self.path.split("?", 1)[1].split("&"):
                if pair.startswith("after="):
                    with contextlib.suppress(ValueError):
                        after = int(pair.split("=", 1)[1])
                    break
        chunks = s.read_output(after)
        self._write_json(200, {
            "ok": True,
            "chunks": [
                {"seq": seq, "data": base64.b64encode(data).decode()}
                for seq, data in chunks
            ],
            "connected": s.connected,
            "closed": s.closed,
            "close_reason": s.close_reason,
            "error": s.error,
            "idle_seconds": int(s.idle_seconds()),
        })

    def _handle_input(self):
        if _SESSION is None or _SESSION.closed:
            self._write_json(200, {"ok": False, "error": "closed"})
            return
        data_b64 = self._read_json().get("data", "")
        try:
            data = base64.b64decode(data_b64)
        except Exception:
            self._write_json(400, {"ok": False, "error": "bad_data"})
            return
        _SESSION.write_input(data)
        self._write_json(200, {"ok": True})

    def _handle_resize(self):
        if _SESSION is None or _SESSION.closed:
            self._write_json(200, {"ok": False, "error": "closed"})
            return
        body = self._read_json()
        cols = int(body.get("cols", 80) or 80)
        rows = int(body.get("rows", 24) or 24)
        _SESSION.resize(cols, rows)
        self._write_json(200, {"ok": True})

    def _handle_close(self):
        # Respond first, then tear down — the client has already
        # gotten what it needed and we don't want a hung wfile.write
        # to block shutdown.
        self._write_json(200, {"ok": True})
        _shutdown()

    _ROUTES = {
        ("GET", "/state"): _handle_state,
        ("GET", "/output"): _handle_output,
        ("POST", "/input"): _handle_input,
        ("POST", "/resize"): _handle_resize,
        ("POST", "/close"): _handle_close,
    }


def _bind_random_port() -> socket.socket:
    """Bind 127.0.0.1:0 and return the open socket. The kernel picks
    a free port; we pass the socket to ThreadingHTTPServer via
    ``server_bind``/``server_activate`` so nothing else can grab the
    port between ``close()`` and ``bind()`` (the classic race).
    """
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("127.0.0.1", 0))
    return sock


def main() -> int:
    global _SESSION, _AUTH_TOKEN, _SERVER

    parser = argparse.ArgumentParser()
    parser.add_argument("--session-id", required=True)
    parser.add_argument("--auth-token", required=True)
    parser.add_argument("--config-file", required=True,
                        help="Path to JSON config. File is deleted "
                             "immediately after reading.")
    args = parser.parse_args()

    # Read the config and delete the file before doing anything
    # else so secrets live on disk for as short as possible.
    with open(args.config_file, "r", encoding="utf-8") as fh:
        config = json.load(fh)
    Path(args.config_file).unlink(missing_ok=True)

    _AUTH_TOKEN = args.auth_token

    logging.basicConfig(
        level=logging.INFO,
        format=f"[terminal-{args.session_id[:8]}] %(levelname)s %(message)s",
        stream=sys.stderr,
    )

    # Re-import ``known_hosts`` from the raw text — the parent strips
    # the asyncssh ``SSHKnownHosts`` object before serialising the
    # config to JSON (that object is not JSON-serialisable).
    ssh_connect_kwargs = dict(config["ssh_connect_kwargs"])
    known_hosts_text = config.get("known_hosts_text") or ""
    if known_hosts_text:
        ssh_connect_kwargs["known_hosts"] = asyncssh.import_known_hosts(
            known_hosts_text,
        )

    _SESSION = TerminalSession(
        session_id=args.session_id,
        ssh_connect_kwargs=ssh_connect_kwargs,
        inst_dir=config["inst_dir"],
        service=config.get("service", "odoo"),
        instance_name=config.get("instance_name", ""),
        environment=config.get("environment", ""),
        user_id=config.get("user_id"),
        welcome_banner=config.get("welcome_banner", ""),
    )

    # Bind the port, report it on stdout so the parent can store it
    # in the route row, then hand the socket over to the HTTP
    # server. ``allow_reuse_address=True`` is already set on the
    # socket above; ThreadingHTTPServer will call ``listen()``.
    bound = _bind_random_port()
    port = bound.getsockname()[1]

    class _Server(ThreadingHTTPServer):
        # Skip the default bind() in the base class — we already
        # bound the socket so the kernel-assigned port is stable.
        def server_bind(self):
            self.socket = bound
            self.server_address = bound.getsockname()

        def server_activate(self):
            self.socket.listen(self.request_queue_size)

    _SERVER = _Server(("127.0.0.1", port), _Handler)

    # First line of stdout = port. Flush so the parent unblocks.
    sys.stdout.write(f"{port}\n")
    sys.stdout.flush()

    signal.signal(signal.SIGTERM, lambda *_: _shutdown())
    signal.signal(signal.SIGINT, lambda *_: _shutdown())

    threading.Thread(target=_watchdog, daemon=True).start()

    try:
        _SERVER.serve_forever()
    finally:
        _shutdown()
    return 0


if __name__ == "__main__":
    sys.exit(main())
