"""Refuse a forged webhook delivery before its body is ever read.

Verifying an HMAC signature means hashing the whole request body: there
is no way to reject a forged signature without first doing the work that
would have validated it. Inside the endpoint that cost can only be
bounded — by size and by frequency — never removed. It disappears only
if the request is refused before it is read, and that has to happen in
front of Odoo.

GitHub publishes the address blocks it delivers from under the ``hooks``
key of ``api.github.com/meta``. A dedicated Traefik router for the
webhook path, carrying an allowlist built from that list, turns the
exposed surface from *the whole internet* into *GitHub's own
infrastructure*.

**Which address the allowlist compares against depends on the host.**
On a host that answers its visitors directly, it is the address the
connection came from. On a host behind a CDN, that address is always the
CDN's edge, so the allowlist has to read the forwarded chain instead —
and reading the forwarded chain is only sound once the proxy in front
has been declared trusted, because Traefik discards the header on every
other connection. Both shapes are rendered from the same routes here;
the caller says which one applies by passing *trusted_proxy*.

**Why the range list has to be refreshed.** The published list changes.
A range added by GitHub and not mirrored here stops deliveries with no
error anywhere: pushes simply stop triggering rebuilds. Every consumer
must treat a failed refresh as "keep the previous list", make the
staleness visible, and pair it with a check that notices the silence.
"""
import re

import yaml

#: Dynamic-config filename. Traefik watches the directory it lives in,
#: so replacing this file reloads the routers with no restart — unlike
#: the trusted-proxy declaration, which is static configuration.
EDGE_CONFIG_FILENAME = "github-webhook.yml"

#: The path the receiving controller is mounted on.
WEBHOOK_PATH = "/cloud/github/webhook"

#: Above the catch-all and the copier-generated per-project routers, so
#: the dedicated router wins for this one path and nothing else.
ROUTER_PRIORITY = 30

#: GitHub caps a webhook delivery at 25 MB. The endpoint already refuses
#: more than this, but that refusal costs a read; refusing at the edge
#: costs nothing. This is the router the limit could never live on
#: globally — a restore upload on the same host needs 2 GiB.
MAX_BODY_BYTES = 32 * 1024 * 1024

ALLOW_MIDDLEWARE = "github-hooks-only"
BODY_MIDDLEWARE = "github-webhook-body"

_HEADER = (
    "# Auto-generated by IncubaCloud. Do not edit by hand.\n"
    "# Source ranges come from api.github.com/meta ('hooks').\n"
)


def route_key(hostname):
    """Return a router name derived from *hostname*.

    Derived rather than counted so re-rendering the same routes produces
    the same document, which is what lets a caller compare documents to
    decide whether anything needs publishing.

    :param str hostname: the host the router matches
    :return: a name safe to use as a Traefik router key
    :rtype: str
    """
    slug = re.sub(r"[^a-z0-9]+", "-", str(hostname).strip().lower())
    return "github-webhook-" + slug.strip("-")


def build_webhook_edge_yaml(routes, ranges, trusted_proxy=False):
    """Render the dynamic config for the allowlisted webhook routers.

    :param routes: mappings with ``hostname`` and either ``service``
        (a cross-provider reference such as ``acme-19-0-prod-main@docker``,
        used as-is) or ``service_url`` (a backend URL, for which a
        load-balancer service is declared here). ``tls_domain`` is
        optional and asks for the router to be served from a wildcard
        certificate rather than one issued for the hostname itself.
    :param ranges: CIDR strings allowed to reach the webhook
    :param bool trusted_proxy: whether a declared, trusted proxy sits in
        front of this host. When it does, the allowlist reads the
        rightmost forwarded entry — the address that proxy saw and
        appended itself. When it does not, it reads the address the
        connection was opened from, because an unproven forwarded header
        is written by whoever is calling.
    :return: a Traefik file-provider document, or ``''`` when there is
        nothing to protect on this host
    :rtype: str
    :raise ValueError: when no range is supplied, since an empty
        allowlist would silently reject every delivery
    """
    entries = [
        str(item).strip() for item in (ranges or []) if str(item).strip()
    ]
    if not entries:
        raise ValueError(
            "Refusing to build an empty webhook allowlist: it would "
            "reject every delivery."
        )
    routers = {}
    services = {}
    for route in routes or []:
        hostname = str(route.get("hostname") or "").strip()
        service = str(route.get("service") or "").strip()
        service_url = str(route.get("service_url") or "").strip()
        if not hostname or not (service or service_url):
            continue
        key = route_key(hostname)
        if not service:
            # A URL cannot be named directly by a router, so the service
            # it stands for is declared alongside it.
            service = key
            services[key] = {
                "loadBalancer": {"servers": [{"url": service_url}]},
            }
        router = {
            "rule": f"Host(`{hostname}`) && Path(`{WEBHOOK_PATH}`)",
            "priority": ROUTER_PRIORITY,
            "entryPoints": ["https"],
            "service": service,
            "middlewares": [ALLOW_MIDDLEWARE, BODY_MIDDLEWARE],
        }
        tls_domain = str(route.get("tls_domain") or "").strip()
        if tls_domain:
            router["tls"] = {
                "certResolver": "letsencrypt",
                "domains": [{"main": tls_domain}],
            }
        else:
            router["tls"] = {"certResolver": "letsencrypt"}
        routers[key] = router
    if not routers:
        return ""

    allow = {"sourceRange": entries}
    if trusted_proxy:
        # depth 1 reads the rightmost forwarded entry: the address the
        # trusted proxy saw and appended. Anything the caller wrote sits
        # to the left of it and is never read. Only sound because the
        # proxy is declared in the static config, which makes Traefik
        # strip the header on every connection that is not the proxy's.
        allow["ipStrategy"] = {"depth": 1}

    document = {
        "http": {
            "routers": routers,
            "middlewares": {
                ALLOW_MIDDLEWARE: {"ipWhiteList": allow},
                BODY_MIDDLEWARE: {
                    "buffering": {"maxRequestBodyBytes": MAX_BODY_BYTES},
                },
            },
        },
    }
    if services:
        document["http"]["services"] = services
    return _HEADER + yaml.safe_dump(document, default_flow_style=False)
